name: "books"
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: base
        restart: unless-stopped
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-extended.ini
        networks:
            - books-network
        depends_on:
            - redis
            - db

    #Nginx Service
    webserver:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - books-network
        depends_on:
            - app

    #MySQL Service
    db:
        image: mysql:8.0
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            "MYSQL_DATABASE": "books"
            "MYSQL_USER": "app"
            "MYSQL_PASSWORD": "password"
            "MYSQL_ALLOW_EMPTY_PASSWORD": "yes"
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/extend.cnf
            - db-data:/var/lib/mysql-books
        networks:
            - books-network

    utility:
        profiles:
            - optional
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: dev
        restart: unless-stopped
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-extended.ini
        networks:
            - books-network
        depends_on:
            - db

    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - books-network

networks:
    books-network:
        driver: bridge

volumes:
    db-data:
        driver: local
